base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from base import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("portfolio.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index_view, name="home"),
]

portfolio/models.py
from django.db import models
from django.utils.html import mark_safe

from . import utils


# Create your models here.
class Recommendation(models.Model):
    name = models.CharField(verbose_name="Имя", max_length=255)
    position = models.CharField(verbose_name="Должность", max_length=300)
    phone = models.CharField(verbose_name="Номер телефона", max_length=20)
    address = models.CharField(verbose_name="Адрес", max_length=255)
    avatar = models.ImageField(upload_to="photos/avatars/", null=True, blank=True, default=None)
    created_at = models.DateTimeField(
        verbose_name="Когда оставлена рекомендация")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Рекомандацию"
        verbose_name_plural = "Рекомандации"


class ResumeCategory(models.Model):
    title = models.CharField(verbose_name="Заголовок в резюме", max_length=255)

    def __str__(self):
        return self.title


class ResumeItem(models.Model):
    working_place = models.CharField(verbose_name="Место работы", max_length=255)
    working_period_from = models.IntegerField(
        verbose_name="Год начала работы",
        choices=utils.year_choices(),
        default=utils.current_year())
    working_period_to = models.IntegerField(
        verbose_name="Год окончания работы",
        choices=utils.year_choices(),
        default=utils.current_year())
    position = models.CharField(verbose_name="Должность", max_length=255)
    resume_category = models.ForeignKey(
        ResumeCategory, on_delete=models.CASCADE, verbose_name="Заголовок в резюме")
    
    def is_current_year(self):
        return self.working_period_to == utils.current_year()
    
    def __str__(self):
        return self.working_place

    class Meta:
        ordering = ["-working_period_to"]


class Skill(models.Model):
    language = models.CharField(verbose_name="Навык", max_length=255)
    progress = models.IntegerField(
        verbose_name="Процент владения навыком", default=0)

    def __str__(self):
        return self.language


class PortfolioProject(models.Model):
    name = models.CharField(verbose_name="Название проекта", max_length=255)
    link = models.URLField(verbose_name="Ссылка на проект")
    photo = models.ImageField(
        verbose_name="Скриншот проекта", upload_to="photos/")
    project_type = models.CharField(verbose_name="Тип проекта", max_length=255)

    @property
    def thumbnail_preview(self):
        if self.photo:
            return mark_safe('<img src="{}" width="50" height="50" />'.format(self.photo.url))
        return ""

    def __str__(self):
        return self.name

portfolio/forms.py
from django import forms


class ContactForm(forms.Form):
    full_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        "placeholder": "Full name",
        "class": "form-input",
        "data-form-input": ""
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "placeholder": "Email address",
        "class": "form-input",
        "data-form-input": ""
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        "placeholder": "Your message",
        "class": "form-input",
        "data-form-input": "",
        "cols": "",
        "rows": "",
    }))

portfolio/views.py
from django.urls import reverse
import requests
from django.conf import settings
from django.shortcuts import HttpResponseRedirect, render, redirect

from . import forms
from . import models
from . import utils

telegram_settings = settings.TELEGRAM

chat_id = 5090318438

url = "https://api.telegram.org/bot{token}/sendMessage?chat_id={chat_id}&text={text}"


def index_view(request):        
    testimonials = models.Recommendation.objects.all()
    resume_categories = models.ResumeCategory.objects.all()
    skills = models.Skill.objects.all()
    portfolio_items = models.PortfolioProject.objects.all()
    if request.method == "POST":
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            full_name = form["full_name"].value()
            email = form["email"].value()
            message = form["message"].value()
            text = f"""
Имя отправителя: {full_name}
Почта отправителя: {email}
Сообщение: {message}            
"""
            requests.post(url.format(
                token=telegram_settings["bot_token"],
                chat_id=chat_id,
                text=text
            ))
            return HttpResponseRedirect(reverse('home'))
    else:
        form = forms.ContactForm()

    context = {
        "testimonials": testimonials,
        "resume_categories": resume_categories,
        "skills": skills,
        "portfolio_items": portfolio_items,
        "projects_types": utils.get_project_types(portfolio_items),
        "form": form
    }

    return render(request, "portfolio/index.html", context)

portfolio/templates/portfolio/components/_about.html
{% load static %}

<article class="about  active" data-page="about">
    {% include 'portfolio/includes/_about/_header.html' %}
    {% include 'portfolio/includes/_about/_about-text.html' %}
    {% include 'portfolio/includes/_about/_service.html' %}
    {% include 'portfolio/includes/_about/_testimonials.html' %}
    {% include 'portfolio/includes/_about/_modal.html' %}
</article>

portfolio/templates/portfolio/components/_contact.html
<article class="contact" data-page="contact">
    {% include 'portfolio/includes/_contact/_header.html' %}
    {% include 'portfolio/includes/_contact/_map.html' %}
    {% include 'portfolio/includes/_contact/_contact-form.html' %}
</article>

portfolio/templates/portfolio/components/_portfolio.html
<article class="portfolio" data-page="portfolio">
    {% include 'portfolio/includes/_portfolio/_header.html' %}
    <section class="projects">
        {% include 'portfolio/includes/_portfolio/_filter-list.html' %}

        <div class="filter-select-box">
            {% include 'portfolio/includes/_portfolio/_filter-select-box.html' %}
        </div>
        {% include 'portfolio/includes/_portfolio/_project-list.html' %}
    </section>
</article>

portfolio/templates/portfolio/components/_resume.html
<article class="resume" data-page="resume">
    {% include 'portfolio/includes/_resume/_header.html' %}
    {% include 'portfolio/includes/_resume/_timelines.html' %}
    {% include 'portfolio/includes/_resume/_skills.html' %}
</article>

portfolio/templates/portfolio/includes/_about/_about-text.html
<section class="about-text">
    <p>Web developer, with extensive knowledge and years of experience, working in web programming.</p>
    <p>My job is to build your website so that it is functional and user-friendly but at the same time attractive.</p>
</section>

portfolio/templates/portfolio/includes/_about/_header.html
<header>
    <h2 class="h2 article-title">About me</h2>
</header>

portfolio/templates/portfolio/includes/_about/_modal.html
{% load static %}

<div class="modal-container" data-modal-container>
    <div class="overlay" data-overlay></div>
    <section class="testimonials-modal">
      <button class="modal-close-btn" data-modal-close-btn>
        <ion-icon name="close-outline"></ion-icon>
      </button>
      <div class="modal-img-wrapper">
        <figure class="modal-avatar-box">
          <img src="{% static 'assets/images/avatar-1.png' %}" alt="Daniel lewis" width="80" data-modal-img>
        </figure>
        <img src="{% static 'assets/images/icon-quote.svg' %}" alt="quote icon">
      </div>
      <div class="modal-content">
        <h4 class="h3 modal-title" data-modal-title>Firdavs Oydinov</h4>
        <time datetime="2021-06-14">14 June, 2021</time>
        <div data-modal-text>
          <p>
            <br>
            Senior Web Developer
            <br>
            <br>
            Phone: +998 (90) 345-17-74
            <br>
            <br>
            Address: Uzbekistan, Tashkent, Chilanzar district
          </p>
        </div>
      </div>
    </section>
  </div>

portfolio/templates/portfolio/includes/_about/_service.html
{% load static %}

<section class="service">
    <h3 class="h3 service-title">What i'm doing</h3>
    <ul class="service-list">
        <li class="service-item">
            <div class="service-icon-box">
                <img src="{% static 'assets/images/icon-dev.svg' %}" alt="Web development icon" width="40">
            </div>
            <div class="service-content-box">
                <h4 class="h4 service-item-title">Web development</h4>
                <p class="service-item-text">
                High-quality development of sites at the professional level.
                </p>
            </div>
        </li>
    </ul>
</section>

portfolio/templates/portfolio/includes/_about/_testimonials.html
{% load static %}
<section class="testimonials">
    <h3 class="h3 testimonials-title">Recommendations</h3>
    <ul class="testimonials-list has-scrollbar">
        {% for testimonial in testimonials %}
            <li class="testimonials-item">
                <div class="content-card" data-testimonials-item>
                    <figure class="testimonials-avatar-box">
                        <img src="{{ testimonial.avatar.url }}" alt="{{ testimonial.name }}" width="60"
                             data-testimonials-avatar>
                    </figure>
                    <h4 class="h4 testimonials-item-title" data-testimonials-title>{{ testimonial.name }}</h4>

                    <div class="testimonials-text" data-testimonials-text>
                        <p>
                            <br>
                            {{ testimonial.position }}
                            <br>
                            <br>
                            Phone: {{ testimonial.phone }}
                            <br>
                            <br>
                            Address: {{ testimonial.address }}
                        </p>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</section>

portfolio/templates/portfolio/includes/_contact/_contact-form.html
<section class="contact-form">
    <h3 class="h3 form-title">Contact Form</h3>
    <form action="/" class="form" data-form method="post">
        {% csrf_token %}
        <div class="input-wrapper">
            {{ form.full_name }}
            {{ form.email }}
        </div>
        {{ form.message }}
        <button class="form-btn" type="submit" data-form-btn>
            <ion-icon name="paper-plane"></ion-icon>
            <span>Send Message</span>
        </button>
    </form>
</section>

portfolio/templates/portfolio/includes/_contact/_header.html
<header>
    <h2 class="h2 article-title">Contact</h2>
</header>

portfolio/templates/portfolio/includes/_contact/_map.html
<section class="mapbox" data-mapbox>
    <figure>
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d1496.901651867664!2d69.29400221312743!3d41.37835802594289!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2s!4v1667921991999!5m2!1sru!2s"
            width="400" height="300" loading="lazy"></iframe>
    </figure>
</section>

portfolio/templates/portfolio/includes/_portfolio/_filter-list.html
<ul class="filter-list">
    <li class="filter-item">
        <button class="active" data-filter-btn>All</button>
    </li>
    {% for projects_type in projects_types %}
        <li class="filter-item">
            <button data-filter-btn>{{ projects_type }}</button>
        </li>
    {% endfor %}
</ul>

portfolio/templates/portfolio/includes/_portfolio/_filter-select-box.html
<button class="filter-select" data-select>
    <div class="select-value" data-selecct-value>Select category</div>
    <div class="select-icon">
        <ion-icon name="chevron-down"></ion-icon>
    </div>
</button>
<ul class="select-list">
    <li class="select-item">
        <button data-select-item>All</button>
    </li>
    {% for projects_type in projects_types %}
    <li class="select-item">
        <button data-select-item>{{ projects_type }}</button>
    </li>
    {% endfor %}
</ul>

portfolio/templates/portfolio/includes/_portfolio/_header.html
<header>
    <h2 class="h2 article-title">Portfolio</h2>
</header>

portfolio/templates/portfolio/includes/_portfolio/_project-list.html
{% load static %}

<ul class="project-list">
    {% for portfolio_item in portfolio_items %}
        <li class="project-item  active" data-filter-item data-category="{{ portfolio_item.project_type|lower }}">
            <a href="{{ portfolio_item.link }}" target="_blank">
                <figure class="project-img">
                    <div class="project-item-icon-box">
                        <ion-icon name="eye-outline"></ion-icon>
                    </div>
                    <img src="{{ portfolio_item.photo.url }}" alt="{{ portfolio_item.name }}" loading="lazy">
                </figure>
                <h3 class="project-title">{{ portfolio_item.name }}</h3>
                <p class="project-category">{{ portfolio_item.project_type }}</p>
            </a>
        </li>
    {% endfor %}
</ul>

portfolio/templates/portfolio/includes/_resume/_header.html
<header>
    <h2 class="h2 article-title">Resume</h2>
</header>

portfolio/templates/portfolio/includes/_resume/_skills.html
<section class="skill">
    <h3 class="h3 skills-title">My skills</h3>
    <ul class="skills-list content-card">
        {% for skill in skills %}
            <li class="skills-item">
                <div class="title-wrapper">
                    <h5 class="h5">{{ skill.language }}</h5>
                    <data value="{{ skill.progress }}">{{ skill.progress }}%</data>
                </div>
                <div class="skill-progress-bg">
                    <div class="skill-progress-fill" style="width: {{ skill.progress }}%;"></div>
                </div>
            </li>
        {% endfor %}
    </ul>
</section>

portfolio/templates/portfolio/includes/_resume/_timelines.html
{% for resume_category in resume_categories %}
    <section class="timeline">
        <div class="title-wrapper">
            <div class="icon-box">
                <ion-icon name="book-outline"></ion-icon>
            </div>
            <h3 class="h3">{{ resume_category }}</h3>
        </div>
        <ol class="timeline-list">
            {% for resumeitem in resume_category.resumeitem_set.all %}
                <li class="timeline-item">
                    <h4 class="h4 timeline-item-title">{{ resumeitem }}</h4>
                    <span>
                        {{ resumeitem.working_period_from }} — 
                        {% if not resumeitem.is_current_year %}
                        {{ resumeitem.working_period_to }}
                        {% else %}
                        Current
                        {% endif %}
                    </span>
                    <p class="timeline-text">{{ resumeitem.position }}</p>
                </li>
            {% endfor %}
        </ol>
    </section>
{% endfor %}

portfolio/templates/portfolio/index.html
{% extends 'base.html' %}

{% block content %}
    {% include 'portfolio/components/_about.html' %}
    {% include 'portfolio/components/_resume.html' %}
    {% include 'portfolio/components/_portfolio.html' %}
    {% include 'portfolio/components/_contact.html' %}
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ABM-CODING Portfolio</title>
  <link rel="shortcut icon" href="{% static 'assets/images/logo-my.svg' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.2/css/all.css" />
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/custom_style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
</head>

<body>
  <main>
    {% include 'components/_sidebar.html' %}
    <div class="main-content">
        {% include 'components/_navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
  </main>


  <script src="{% static 'assets/js/script.js' %}"></script>

  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

  <script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.13.0/firebase-app.js";
    const firebaseConfig = {
      apiKey: "AIzaSyAWOioye5beOx3r--LD7hsMBpn-wme4_Ag",
      authDomain: "portfolio-ba35f.firebaseapp.com",
      projectId: "portfolio-ba35f",
      storageBucket: "portfolio-ba35f.appspot.com",
      messagingSenderId: "282878344620",
      appId: "1:282878344620:web:37e8d80296e466a8bd4e09"
    };
    const app = initializeApp(firebaseConfig);
  </script>

</body>

</html>

templates/components/_navbar.html
<nav class="navbar">
  <ul class="navbar-list">
    <li class="navbar-item">
      <button class="navbar-link  active" data-nav-link>About</button>
    </li>
    <li class="navbar-item">
      <button class="navbar-link" data-nav-link>Resume</button>
    </li>
    <li class="navbar-item">
      <button class="navbar-link" data-nav-link>Portfolio</button>
    </li>
    <li class="navbar-item">
      <button class="navbar-link" data-nav-link>Contact</button>
    </li>
  </ul>
</nav>

templates/components/_sidebar.html
<aside class="sidebar" data-sidebar>
  {% include '../includes/_sidebar/_sidebar-info.html' %}

  <div class="sidebar-info_more">
    <div class="separator"></div>
    {% include '../includes/_sidebar/_contacts-list.html' %}
    <div class="separator"></div>
    {% include '../includes/_sidebar/_social-list.html' %}
  </div>
</aside>

templates/includes/_sidebar/_contacts-list.html
<ul class="contacts-list">
    <li class="contact-item">
      <div class="icon-box">
        <ion-icon name="mail-outline"></ion-icon>
      </div>
      <div class="contact-info">
        <p class="contact-title">Email</p>
        <a href="mailto:abdulmalikakhzamov1@gmail.com" class="contact-link">abdulmalikakhzamov1@gmail.com</a>
      </div>
    </li>
    <li class="contact-item">
      <div class="icon-box">
        <ion-icon name="phone-portrait-outline"></ion-icon>
      </div>
      <div class="contact-info">
        <p class="contact-title">Phone</p>
        <a href="tel:+998331131333" class="contact-link">+998(33)113-13-33</a>
      </div>
    </li>
    <li class="contact-item">
      <div class="icon-box">
        <ion-icon name="calendar-outline"></ion-icon>
      </div>
      <div class="contact-info">
        <p class="contact-title">Birth</p>
        <time datetime="1982-06-23">July 24, 1999</time>
      </div>
    </li>
    <li class="contact-item">
      <div class="icon-box">
        <ion-icon name="location-outline"></ion-icon>
      </div>
      <div class="contact-info">
        <p class="contact-title">Адрес</p>
        <address>Uzbekistan, Tashkent, Yunusabad district, quarter 12, building 13, apartment 22</address>
      </div>
    </li>
  </ul>

templates/includes/_sidebar/_sidebar-info.html
{% load static %}

<div class="sidebar-info">
    <figure class="avatar-box">
      <img src="{% static 'assets/images/my-avatar.jpg' %}" alt="AbdulMalik Akhzamov" width="80">
    </figure>
    <div class="info-content">
      <h1 class="name" title="Richard hanrick">AbdulMalik Akhzamov</h1>
      <p class="title">Web Developer</p>
    </div>
    <button class="info_more-btn" data-sidebar-btn>
      <span>Show Contacts</span>
      <ion-icon name="chevron-down"></ion-icon>
    </button>
  </div>

templates/includes/_sidebar/_social-list.html
<ul class="social-list">
    <li class="social-item">
        <a href="https://www.linkedin.com/in/abdulmalik-akhzamov-890b01242/" class="social-link" target="_blank">
        <i class="fab fa-linkedin"></i>
        </a>
    </li>
    <li class="social-item">
        <a href="https://t.me/abdulmalik_akhzamov" class="social-link" target="_blank">
        <i class="fab fa-telegram"></i>
        </a>
    </li>
    <li class="social-item">
        <a href="https://www.instagram.com/abdulmalik_akhzamov/" class="social-link" target="_blank">
        <i class="fab fa-instagram"></i>
        </a>
    </li>
</ul>